CREATE TABLE PROXY_HISTORY(
LOG_CONTEXT VARCHAR NOT NULL,
MESSAGE_REF INT NOT NULL,
PROTOCOL VARCHAR NOT NULL,
HOST VARCHAR NOT NULL,
PORT INT DEFAULT 0,
CLIENT_IP VARCHAR NOT NULL,
URL VARCHAR NOT NULL,
REQUEST_METHOD VARCHAR NOT NULL,
REQUEST_BYTES BINARY,
REQUEST_CHARSET VARCHAR DEFAULT 'UTF-8',
RESPONSE_STATUS_CODE SMALLINT DEFAULT 0, 
RESPONSE_BYTES BINARY,
RESPONSE_CHARSET VARCHAR DEFAULT 'UTF-8',
SEND_AT TIMESTAMP DEFAULT NOW(),
RECEIVED_AT TIMESTAMP DEFAULT NOW(),
PRIMARY KEY (LOG_CONTEXT, MESSAGE_REF)
);
